# Generated by Django 5.0.6 on 2024-07-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
