# Generated by Django 4.1.2 on 2024-07-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_cliente_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['rut']},
        ),
    ]
